#+TITLE: Doom Academic Config
#+AUTHOR: Bruce D'Arcus

* Introduction

This is my configuration file for ~org~, ~org-roam~, ~org-ref~, etc in Doom. In it, I
am trying to stitch together an elegant editing environment, primarily for
academic note-taking, bibliographic management, writing and publishing.

Note: I work at the border of the social sciences and humanities. No math or
statistics, for example, and heavy on quoting of primary source documents.

* Tasks and Questions

** TODO review and refine org-ref config
** TODO do I want to integrate ebib? if yes, how?
** TODO investigate integrating paragraph folding into org visibility cycling

** TODO best relationship between org-ref and org-roam capture?

* Org, Including Bibliographic Integration

This is the core of my academic workflow.

Goal: a beautifully-integrated academic note-taking, bibliographic management,
and manuscript outlining and editing environment.

** Org-Roam

Org-roam is my primary note-taking and idea-development tool.

Doom now has a +roam flag, so there's not much config needed.

#+BEGIN_SRC elisp
(setq org-roam-directory "~/org/roam")
(setq org-roam-graph-executable "/usr/bin/dot")
(setq org-roam-graph-extra-config '(("overlap" . "false")))
(setq org-roam-graph-node-extra-config '(("style" . "filled")
                                         ("fillcolor" . "skyblue")
                                         ("shape" . "note")
                                         ("fontname" . "Fira Sans")))
#+END_SRC


** Bibliographic Management and Integration

This is the setup for integrating citations in the editing workflow.

First, setup ~org-ref~, borrowing from [[https://github.com/fuxialexander/doom-emacs-private-xfu/blob/master/modules/tools/reference/config.el][this module]].

Need to fix the capture template to fit with ~org-roam~, and add key bindings.

What I want, per below, is for opening a note in ~org-ref~ to work the same as
~org-roam-find-file~, creating a new note if it does not exist.

#+BEGIN_SRC elisp
(use-package! org-ref
  :commands (org-ref-bibtex-next-entry
             org-ref-bibtex-previous-entry
             doi-utils-get-bibtex-entry-pdf
             org-ref-ivy-insert-cite-link
             org-ref-find-bibliography
             org-ref-open-in-browser
             org-ref-open-bibtex-notes
             org-ref-open-bibtex-pdf
             org-ref-bibtex-hydra/body
             org-ref-bibtex-hydra/org-ref-bibtex-new-entry/body-and-exit
             org-ref-sort-bibtex-entry
             arxiv-add-bibtex-entry
             arxiv-get-pdf-add-bibtex-entry
             doi-utils-add-bibtex-entry-from-doi
             isbn-to-bibtex
             pubmed-insert-bibtex-from-pmid)
  :init
  (when (featurep! :completion helm)
    (setq org-ref-completion-library 'org-ref-helm-bibtex))
  (when (featurep! :completion ivy)
    (setq org-ref-completion-library 'org-ref-ivy-cite))
  :config
  (setq
    orhc-bibtex-cache-file (concat doom-cache-dir "org-ref.cache")
    org-ref-get-pdf-filename-function
    (lambda (key) (car (bibtex-completion-find-pdf key)))
    org-ref-notes-function
    (lambda (thekey)
      (let* ((results (org-ref-get-bibtex-key-and-file thekey))
             (key (car results))
             (bibfile (cdr results)))
        (save-excursion
          (with-temp-buffer
            (insert-file-contents bibfile)
            (bibtex-set-dialect (parsebib-find-bibtex-dialect) t)
            (bibtex-search-entry key)
            (org-ref-open-bibtex-notes)))))
    org-ref-create-notes-hook
    '((lambda ()
        (org-narrow-to-subtree)
        (insert (format "cite:%s\n" (org-entry-get (point) "CUSTOM_ID")))))
    org-ref-note-title-format "* TODO %t
 :PROPERTIES:
  :CUSTOM_ID: %k
 :END:
")
  (when (eq +reference-field 'bioinfo)
    (require 'org-ref-biorxiv)
    (add-to-list 'doi-utils-pdf-url-functions 'oup-pdf-url)
    (add-to-list 'doi-utils-pdf-url-functions 'bmc-pdf-url)
    (add-to-list 'doi-utils-pdf-url-functions 'biorxiv-pdf-url))
  (when IS-MAC
    (setq doi-utils-pdf-url-functions
          (delete 'generic-full-pdf-url doi-utils-pdf-url-functions))
    (add-to-list 'doi-utils-pdf-url-functions 'generic-as-get-pdf-url t)))
#+END_SRC

Key binding config (though not sure this works ATM):

#+BEGIN_SRC elisp
(:after bibtex
  :map bibtex-mode-map
  "s-." #'org-ref-bibtex-hydra/body)
#+END_SRC

While I still use Zotero to grab citation data, I export that content to a single biblatex file.

#+BEGIN_SRC elisp
(setq bibtex-dialect 'biblatex)
(setq bibtex-completion-bibliography
      '("~/org/bib/academic.bib"
        "~/org/bib/me.bib"))
#+END_SRC

#+BEGIN_SRC elisp
(setq bibtex-completion-format-citation-functions
      '((org-mode      . bibtex-completion-format-citation-org-link-to-PDF)
        (latex-mode    . bibtex-completion-format-citation-cite)
        (markdown-mode . bibtex-completion-format-citation-pandoc-citeproc)
        (default       . bibtex-completion-format-citation-default)))

(setq bibtex-completion-notes-path "~/org/roam/biblio")
(setq ivy-bibtex-default-action 'ivy-bibtex-insert-citation)
#+END_SRC

Now adding a binding to bring up ~ivy-bibtex~ for citation insertion in
~markdown-mode~.

#+BEGIN_SRC elisp
(map!
 :map (markdown-mode-map)
 :localleader
 :desc "insert citation" "ic" #'ivy-bibtex)
#+END_SRC

** Integration

~Org-roam~ will soon have ~org-ref~ support, which will display cite links in the
buffer. To put this all together, we will have two types of notes:

- content notes :: these are org-roam notes with standard links
- bibliographic notes :: these are lower-level notes on biliographic source
  content and quotes; within org-roam we designate them by adding a ~#+ROAM_KEY~
  id that references the source citekey

As for the workflow to take bibliographic notes, perhaps it is best to start
from the bib file source record and use ~org-ref~ to create the note, using the
citekey as filename? We'll store these in a dedicated subdirectory, though I'm
not sure if that's necessary.

#+BEGIN_SRC elisp
(setq bibtex-completion-notes-path "~/org/roam/biblio")
#+END_SRC

** Paragraph Folding

Ideally, I want paragraph folding integrated into org visibility cycling. But
this is close enough for now; folds all paragraphs in a document to the first
line. This is helpful for long documents.

#+BEGIN_SRC elisp
(use-package! origami
  :commands (origami-toggle-node origami-toggle-all-nodes)
  :hook (text-mode . origami-mode)
  :init
  :config
  (map! :leader
        :prefix "t"
        :desc "Origami-Toggle All Nodes" "O" #'origami-toggle-all-nodes
        :desc "Origami-Toggle Node" "o" #'origami-toggle-node)
  )
#+END_SRC

* Publishing

Using a combination of Pandoc, Hugo and (less so) LaTeX.

* Projects

I am currently torn about how project files and directories should relate to
org-roam. Typically in editing environments, a project is a folder, and in org,
a profile file is an org file within that folder.

In zettelkasten, typically directories are flat, since you basically are
constructing a graph, and you want to avoid premature or unnecessary hierarchy.

Current thought is that projects emerge up out of the braindump, something like:

1. first develop structure notes that are the outline of the ideas, where the
   outline is mostly import statements for existing notes (see below example)
2. export that outline note to a consolidated org file, in a dedicated
   ~/Projects directory.
3. develop manuscript there, outside of the braindump

#+BEGIN_EXAMPLE
#+INCLUDE: "~/my-book/chapter2.org" :minlevel 1
#+END_EXAMPLE
