#+TITLE: Doom Academic Config
#+AUTHOR: Bruce D'Arcus

* Introduction

This is my configuration file for ~org~, ~org-roam~, ~org-ref~, etc in Doom. In it, I
am trying to stitch together an elegant editing environment, primarily for
academic note-taking, bibliographic management, writing and publishing.

Note: I work at the border of the social sciences and humanities. No math or
statistics, for example, and heavy on quoting of primary source documents.

* Tasks and Questions

** TODO keybindings for org-ref, etc
** TODO do I want to integrate ebib? if yes, how?
** TODO investigate integrating paragraph folding into org visibility cycling

** TODO best relationship between org-ref and org-roam capture?

* Org, Including Bibliographic Integration

This is the core of my academic workflow.

Goal: a beautifully-integrated academic note-taking, bibliographic management,
and manuscript outlining and editing environment.

** Org-Roam

Org-roam is my primary note-taking and idea-development tool.

Doom now has a +roam flag, so there's not much config needed.

#+BEGIN_SRC elisp
(setq org-roam-directory "~/org/roam")
(setq org-roam-graph-executable "/usr/bin/dot")
(setq org-roam-graph-extra-config '(("overlap" . "false")))
(setq org-roam-graph-node-extra-config '(("style" . "filled")
                                         ("fillcolor" . "skyblue")
                                         ("shape" . "note")
                                         ("fontname" . "Fira Sans")))
#+END_SRC

Turn-off spell checking on the org-roam buffer.

#+BEGIN_SRC elisp
(add-hook 'org-roam-backlinks-mode-hook (lambda () (flyspell-mode -1)))
#+END_SRC

** Bibliographic Management and Integration

This is the setup for integrating citations in the editing workflow, using ~ivy/helm-bibtex~.

#+BEGIN_SRC elisp
(use-package! ivy-bibtex
  :when (featurep! :completion ivy)
  :commands (ivy-bibtex)
  :config
  (setq ivy-bibtex-default-action 'ivy-bibtex-insert-key)
  (add-to-list 'ivy-re-builders-alist '(ivy-bibtex . ivy--regex-plus)))

(use-package! helm-bibtex
  :when (featurep! :completion helm)
  :commands helm-bibtex)

(setq bibtex-completion-bibliography "~/org/bib/academic.bib")
(setq bibtex-completion-library-path "~/org/pdf")
(setq bibtex-completion-pdf-field "File")
(setq bibtex-completion-notes-path "~/org/roam/biblio")
#+END_SRC

Define the citation format to use in different document formats.

#+BEGIN_SRC elisp
(setq bibtex-completion-format-citation-functions
      '((org-mode      . bibtex-completion-format-citation-pandoc-citeproc)
        (latex-mode    . bibtex-completion-format-citation-cite)
        (markdown-mode . bibtex-completion-format-citation-pandoc-citeproc)
        (default       . bibtex-completion-format-citation-default)))
#+END_SRC

Now adding a binding to bring up ~ivy-bibtex~ for citation insertion in
~markdown-mode~, ~org~, and ~latex-mode~.

#+BEGIN_SRC elisp
(map! :leader
 :map (org-mode-map markdown-mode-map latex-mode-map)
 (:prefix("i" . "insert")
 :desc "Citation" "c" #'ivy-bibtex))
#+END_SRC

Define the ~bibtex-completion~ template to include ~ROAM_KEY~.

#+BEGIN_SRC elisp
(setq
        bibtex-completion-notes-template-multiple-files
       "${title} : (${=key=})
,#+ROAM_KEY: cite:${=key=}
- tags ::
- keywords :: ${keywords}
\n* ${title}\n  :PROPERTIES:\n  :Custom_ID: ${=key=}\n  :URL: ${url}\n  :AUTHOR: ${author-or-editor}\n  :NOTER_DOCUMENT: /${file}\n  :NOTER_PAGE: \n  :end:\n\n")
#+END_SRC

Setting up ~org-ref~, primarily to provide better two-way integration between
~org~ and ~org-roam~ and bibliographic entries.

#+BEGIN_SRC elisp
(use-package! org-ref
  :after (org ivy-bibtex helm-bibtex)
  :init
  (when (featurep! :completion ivy)
    (setq org-ref-completion-library 'org-ref-ivy-cite))
  (when (featurep! :completion helm)
    (setq org-ref-completion-library 'org-ref-helm-bibtex))
  (setq org-ref-notes-directory "~/org/roam/biblio"
        org-ref-default-bibliography '("~/org/bib/academic.bib")
        bibtex-completion-bibliography '("~/org/bib/academic.bib")
        bibtex-autokey-year-length 4
        bibtex-autokey-name-year-separator "-"
        bibtex-autokey-year-title-separator "-"
        bibtex-autokey-titleword-separator "-"
        bibtex-autokey-titlewords 3
        bibtex-autokey-titlewords-stretch 1
        bibtex-autokey-titleword-length 5))
#+END_SRC

Setup ~org-noter~ to integrate note-taking for PDF documents.

#+BEGIN_SRC elisp
(use-package! org-noter
    :after org
    ; FIXME how to get it to look for citekey-based filenames?
    :config (setq org-noter-auto-save-last-location t
                  org-noter-notes-search-path '("~/org/roam/biblio/")
                  org-noter-separate-notes-from-heading t))
#+END_SRC

Key binding config for bibtex:

#+BEGIN_SRC elisp
(use-package! bibtex
  :defer t
  :config
  (setq bibtex-dialect 'biblatex
        bibtex-align-at-equal-sign t
        bibtex-text-indentation 20)
  (map! :map bibtex-mode-map
        ; FIXME
        :localleader
        (:prefix("o" . "open")
          :desc "Bibliographic Note" ""))
#+END_SRC


** Integration

~Org-roam~ will soon have ~org-ref~ support, which will display cite links in the
buffer. To put this all together, we will have two types of notes:

- content notes :: these are org-roam notes with standard links
- bibliographic notes :: these are lower-level notes on biliographic source
  content and quotes; within org-roam we designate them by adding a ~#+ROAM_KEY~
  id that references the source citekey

** Paragraph Folding

Ideally, I want paragraph folding integrated into org visibility cycling. But
this is close enough for now; folds all paragraphs in a document to the first
line. This is helpful for long documents.

#+BEGIN_SRC elisp
(use-package! origami
  :commands (origami-toggle-node origami-toggle-all-nodes)
  :hook (text-mode . origami-mode)
  :init
  :config
  (map! :leader
        :prefix "t"
        :desc "Origami-Toggle All Nodes" "O" #'origami-toggle-all-nodes
        :desc "Origami-Toggle Node" "o" #'origami-toggle-node)
  )
#+END_SRC

* Publishing

Using a combination of Pandoc, Hugo and (less so) LaTeX.

* Projects

I am currently torn about how project files and directories should relate to
org-roam. Typically in editing environments, a project is a folder, and in org,
a profile file is an org file within that folder.

In zettelkasten, typically directories are flat, since you basically are
constructing a graph, and you want to avoid premature or unnecessary hierarchy.

Current thought is that projects emerge up out of the braindump, something like:

1. first develop structure notes that are the outline of the ideas, where the
   outline is mostly import statements for existing notes (see below example)
2. export that outline note to a consolidated org file, in a dedicated
   ~/Projects directory.
3. develop manuscript there, outside of the braindump

#+BEGIN_EXAMPLE
#+INCLUDE: "~/my-book/chapter2.org" :minlevel 1
#+END_EXAMPLE
