(package! org-ref)
(when (featurep! :completion ivy)
    (package! ivy-bibtex))
(when (featurep! :completion helm)
    (package! helm-bibtex))

(package! pandoc-mode)
(package! org-super-agenda)
(package! org-chef)
;(package! golden-ratio)
(package! org-fancy-priorities)
(package! origami)
;(package! ebib)
(unpin! org-roam)
