(package! org-ref)
(package! org-roam :recipe (:host github :repo "jethrokuan/org-roam" :branch "develop"))
(package! pandoc-mode)
(package! org-super-agenda)
(package! org-chef)
;(package! golden-ratio)
(package! org-fancy-priorities)
(package! origami)
